name: bokbokpc
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME  # Replace with your actual GitHub repo
    branch: main  # or master, depending on your default branch
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /
    initial_delay_seconds: 300
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: YAHOO_CLIENT_ID
    value: ${YAHOO_CLIENT_ID}  # Set this in DigitalOcean dashboard
    type: SECRET
  - key: YAHOO_CLIENT_SECRET
    value: ${YAHOO_CLIENT_SECRET}  # Set this in DigitalOcean dashboard
    type: SECRET
  - key: YAHOO_REDIRECT_URI
    value: ${YAHOO_REDIRECT_URI}  # Set this in DigitalOcean dashboard
    type: SECRET
  - key: FRONTEND_URL
    value: https://bokbokpc.info  # Update with your actual domain
